day12();


function day12() {
    //Area -> number of garden plots of the region
    //Perimeter -> number of adjacent flowers to the area
    const solution = totalTrailheadScore();
    console.log("THE SOLUTION FOR THE 12TH DAY OF CODE ADVENT IS: " + solution);
}

function getInputData() {
    return  "SSSSSSSSQQQQQQQUUUUUUUUBBBBBBBBBBBBBBBBBBBBBNNNNNNNNVVVVVVOIIIIIIIIIIIIILLLLLLLLLLLLLLTTSSSSSSSSSGGGGGGGGGGGGGGGGGKKKKKKKKKJJJJJJJJJJJJJJJJJ\n" +
            "SSSSSSSSQQQQQQUUUUUUEUUUUSBBBBBBBBBBBBBBBBBVVNVGNGNVVVVVOOOIIIIIIIIIIIIILLLLLLLLLLLLLLLLSSSSSSSSSGGGGGGGGGGGGGGGGGKKKKKKKKKKJJJJJJJJJJJJJJJJ\n" +
            "SSSSSSSQQQQQQQQUUUUUUUUUUBBUBBBBBBBBBBBBBBVVVGGGGGNVVVVVOOOIIIIIIIIIIIIILLLLLLLLLLLLLLLSSSSSSSSSSSGGGGGGGGGGGGGGGGKKSKKKKKKJJJJJJJJJJJSJJSSJ\n" +
            "SKSKKSSKQQQQQUUUUUUUUUUUUUUUBBBBBBBBBBBBBBBVGRGGGGGVVVVOOOOOOOIIIIIIIIIILLLLLLLLLLLLLLLSSSSSSSSSSSGGGGGGGGGGGGGGGGKKSKKKKKJJJJJJJJJJJJSJSSSJ\n" +
            "SKKKKKSKQQQQQUUUUUUUUUUUUUUQBBBBBBBBBBBBBBBGGGGGGGCOOOOOOOOOOIIIIIIIIIIIILLLLLLLLLLLLLSSSSSSSSSSSSSOGGGGGGGGGGGGGGGKSSSKKJJJJJJJJJJJJSSSSSSJ\n" +
            "SKKKKKKKKKQQQUQQUUUUUUUUUUUQBBBBBBBBBBBBBGGGGGGGGCCCOOOOOOOOOIIOOIIIIIIIILLLLLLLLLLLLLLSSSSSSSSSSSSGGGGGGGGGGGGGGGGSSSSJJJJJJJJJJJJJJSSSSSSJ\n" +
            "KKKKKKKKKKQQQQQQUUUUUUUUUUUBBBBBBBBBBBBBGGGGGGGGGGKKZZOOOOOOOOOOOOIIIIIILLLLLLLLLLLLLLLLSSSSSSSSSSSSGGGGGGGGGGGGGSSSSAAJJJJJJJJJJJNNNNNSSSSS\n" +
            "KKKKKKKKKKQQQQQQQUUUUUUUUUBBBQBBBBBBBGGGGGGGGGGGKNKKKZOOOOOOOOOOOOIIIIIIILQLLLLLLLLLLOLLSSSSSSSSSSSGGGGGGGGGGGGGSSSSSAJJNJJJJJJOJJNNNNSSSSSS\n" +
            "DKKKKKKKKKQQQQQQQUUUUUUUUUBQQQBBBVBGGGGGGGGGGGGGKKKKKOOOOOOOOOOOOOOOIIIIIIQLLLLLLLLLLSSSSSSSSSSSSSSGGGGGGGGGGGGSSSSSSSILNLEEJEJJJJJNNNNNSSSS\n" +
            "DDKKKKKKQQQQQQQQQUUUUUUUQQQQQBBBBBCCGGGGGGGGGQGGAKKKKKOOOOOOOOOOOOOIIIIIILLLLLLLLLLLLSSSSSSSSSSSSSVVVVVGGGGGGGGSSSSSSIILLLEEEEJFJJNNNNNNSSSS\n" +
            "CCCKCCCCQQQQQQQQQUUUUUUUUUQQQQBBBBCCNGGGGGGGGGGGKKKKKPPOOOOOOOOOOOOOIIIIGLXXXXLLLLLSSSSSSSSSSSSSSSSVVVVVVGGSSSSSSSSSIIILLLLEEEEJJJNNNNNNNNSS\n" +
            "CCCCCCCCQQQQQQQQUUUUUUUUUAIQIQBBIICCNNGGGGGFGGKKKKKKKKKZOOOOOOOOOOOOIIIIGXXXXXXXSSSSSSSSSSSSSSSDSSSVVOVVVGVSSSSSSSSSILLLLLLEEEVVONNNNNNNYYYY\n" +
            "QCCCCCCCQQQQQQQUUUUUUUUUUIIIIIIKIIICNNGGGGFFFFFFFKKKKKZZOOOOOOOOOOOYIIIIIXXXXXXSSSSSSSSSSSSDDRSSSSSOOOVVVGVSSSSSSSSIILLLLLLLLVVVVBNNNNNYYYYY\n" +
            "QCCCCCCCQQQQQQIUUUUUUUUUIITIIIIKIININNNNNNNFFFFFKKKKZZZZOOOOOOOOOOOYYIIIXXXXXXXGSSSSSSSSSSSSDDUUSOOOOVVVVVVSASSYYYSLLLLLLLVVVVVVBBNNNNNNYYYY\n" +
            "QCCCCCCCCQQQQQIUUUKUUUMMMMMMIIIIIIIINNNNNNNNFFFFKKKZZZZZOOOOOOOOYYYYYIIIXXXXXXXGGSSSSSSSSSSSDUUUSGOOOVVVRRRSSSSYYYYLLLLLLLVVVVVVVBYNNNYYYYYY\n" +
            "QCCCCVVCCVQQQQQKKDKUUUMMMMMMMMMMMMINNNNNNNNEFEFFFKKKZZZZZOOOOOOOYYYYXXXXXXXXXXXGSSSSSSSSSSSSDDUUUOOOVOOVVVRRSRSSYYYYLLLLLLVVVVVVVVYYYNYYYYYY\n" +
            "QQCCVVVVVVQQQQQKKKKKKUMMMMMMMMMMMMNNNNNNNNNEEEFEEZZZZZZZZZOOOOOOYYYYXXXXXXXXKKKGGSSJSSSJSSSDDDDOOOOOOOOVRRRRSRRRRYYLLLLLVVVVVVVVVYYYYNYYYYYY\n" +
            "QQQQQVVVVQQQQQKKKKKKKKMMMMMMMMMMMMNNNNNNNEEEEEEEZZZZZZZZZOOOOOOOYYYYYXXXXXXKKKKKKKSJJJSJSJSDDDDOOOOOOOOVRRRRRRRRRRYYLVLVVVVVVVVVVVYYYYYYYYYY\n" +
            "QQQQVVVVVVQRQQKKKKKKKRMMMMMMMMMMMMNNNNNNNENNNEZZZZZZZZZZTTTTTTTTTYYXYXXXXXXKKKKKKJJJJJJJJJJDDDDDOOOOOOORLRRRRRRRRRRYYVVVVVVVVVVVVVYYYYYYYYYY\n" +
            "QQQQQQVVVVVQQQQKKKKKKKMMMMMMEEEEEEENNNNNNNNNNEEZZZZZZZZZTTTTTTTTTXXXXXXXXXKTKKKKKJJJJJJJJJJDDDDOOOOOYOORRRRRRRRRRRRRVVVVVVVVVVVVZZKYYYYYYYYY\n" +
            "QQQQQVVVVVKKQQKKKKKKKKMMMMMMEEEEEEENNNNNNNNNNNZZZZZZZZZYTTTTTTTTTXXXXXXXXXKKKKKKKJJJJJJJJJSSSOOOOOOOYRRRRRRRRRRRRRRRDDVVVVVVVVVVVZKYYYYYYYYY\n" +
            "QQQQQQQQQVKKKKKKKKKKKKKKKKWIEEEEEEENLLLNNLLFNZZZZZZZZZZZTTTTTTTTTXXXXXXXXKKKKKKKKJJJJJJJJSSSSSSSOOOOOORRRRRRRRRRRRRRDVVVVVVVVVVVVKKKKKYYYYYY\n" +
            "QQQQQQQVVVKKKKKKKKKKKKKKKKKKEEEEEEENLLLLLLFFNZZTTTTTTTTTTTTTTTTTTXXXXXXXXXKKKKKKKKJJJJJJJJSSSJJSOOOOOOORRRRRRRRRRRRRDVVVVVVVJJVVVKKKKKYYYYYY\n" +
            "IIIIIQQQVKKKKKKKKKKKKKKKKDDKEEEEEEENNYLLLLLLZZZTTTTTTTTTTTTTTTTTXXXXXXXXXXKKKKIKKJJJJJJJJJSJJJJOOOOOOOORRRRRRRRRRRRRDVVVVVVVVKVKKKKKKKKYYYYY\n" +
            "IIIIIQIVVVVVKKKKKKWKDKDDDDDDEEEEEEETTLLLLLLLZZZTTTTTTTTTTTTYOYYYXXXBXXXXXXXXKIIIKKKJJJJJJJJJJJJOROOOOOORRRRRRRRRRRRDDVVVVVVVUKKKKKKKKKKKYYYY\n" +
            "IIIIIIIVVVVVYKKKKKKDDDDDDDDDEEEEEEETTLLLLLLLLZTTTTTTTTTTTTTYYYYYYYBBBXXXXXXXXIIIKKKUJJJJJJJJJJJOOOOOOOOOOORRRRRRRRRDDVVVVVVUUUKKKKKKKKKKZYYY\n" +
            "IIIIIIVVVVVVKKKKKKKSDDDDDDEEEEEEEEEEELLLLLLLLZTTTTTTTTTTTTTYYYYYYEBBBBXXXXVVXKKKDKKUKKJJJJJJCCCCCOOOOOOOOORMRMRMMMDDDDDVVVUUUUKKKKKKKKKZZYYY\n" +
            "IIIIIIVVVVVVKIKKKKDDDDDDDDDEEEEEEEEEELLLLLLLETTTTTTTTTTTTYYYYYYYYYBBBBBXXXVVKKKKDKKKKKJJJJJJCCCCCOOOOOOOOOOMMMMMMMDDDDDDVVVUUUUKKKKKKKKKZOOY\n" +
            "IIIIIIIVVVVVKIKKKKDDDDDDDDDEEEEEEEEEEILLLLLLETTTTTTTTTTTTYYYYYYYYYYYTBBUXDVVKKKKKKKKKKKJJJXJCCCCCOOOOOOOOOOMMMMMMMDDDDSVVVUUUIIIIQKKKKKKZOOQ\n" +
            "JIJIIIIVVVVIIIIIIIIDDDDDDEDEEEEEEEEEEEEEELLLETTTTTTTTTTTTTTTTTTTTTYTTTUUUDDVKKKKKKKKKIXJJXXXCCCCCOOOOOOOORMMMMMMMMMDDSSSSUUIIIIIKKKKKKKOOOOQ\n" +
            "JJJJIIIVVIVVIIIIIIIIXXDDDEEEEEEEEEEEEEEEEQQQEETTTTTTTTTTTTTTTTTTTTTTTTUDDDQKKKKKKKKKXXXJJJXXCCCCCOOOOOOOOOMMMMMMMMMMDSSSSSSSIIIIKKKKKNKKOOQQ\n" +
            "JJJJJIIIIIIIIIIIMIIIXXEEEEEEEEEEEEEEEEEEEQQQEQTTTTTTTTTTTTTTTTTTTTTTTTUDDDDDDKKKKKKXXXXXXXXXCCCCCOOOOOOOOQMMMMMIMMMMSSSSSSSSIIIIIIKKKKKKOQQY\n" +
            "JJJJJIIIIIIIIIIIIIIXXXLEEEEEEEEEEEEEEEEEEQQQQQTTTTTTTTTTTTTTTTTTTTTTDDDDDDDDDKKKKKKXXXXXXXXCCCCCCCCCOOOOOOFMMFFMMMMHHSSSSSSSSIIIIIIKIKIIYYYY\n" +
            "JJJJJIIIIIIIIIIIIIXXXLLLLLEEEEEEEFREEEEEEQQQQQQTTTTTTTTTTTTTTTTTTTTTTDDDDDDDDDKKKKXXXXXXXXXCCCCCCCCCOOOFFFFFFFMMMMHHSSSSSSSSSIIIIIIIIIIIYYYY\n" +
            "JJJJJKIIIIIIKIIILQLLXLLLLLEEEEFFFFREEEEEEQQQQQQTTTTTTTTTTTTTTTTTTTTTTDDDDDDDKKKKKKKKXXXXXXXCCCCCCCCCCCFFFFFFFFFFMMMSSSSSSSSSIIIIIIIIIYYYYYYY\n" +
            "JJJJJKKKKKKKKRIYLLLLLLLLLLLEEEFFFFFEEEEEEQQQQQQTTTTTTTTTTTTTTDVDDDTTTTDDDDDDKKKKKKKKKXXXXXXCCCCCCCCCCCFFFFFFFFFFFFSSFSSSSSSSISSIIIIYYYYYYYYY\n" +
            "JJJJJKKKFFKKKKYYYLLLLLLLLLLEEFFFFFFEEEEEEQQQQQQTTTTTTTTTTTTDDDDDDDTTTTDDDDDDDKKKKKKKKXXXXXXXXUUUUUUCCCFFFFFFFFFFFFFFFSSSSSSSSSSIIIIIYYYYYYYY\n" +
            "JJKKKKKKKKKKYYYYYLLLLLLLLLLENNNFVFFFFFFQQQQQQQQQTTTTTNTTTTDDDDDDDDTTTDDDKDDKKKKKKKKKKXXDXHXOUUUUUUUCCCFFFFFFFZFFZFFFFFESFFCFSSKIIXIIYYYYYYYY\n" +
            "JJJJKKKKKKKKKKYYYYYLLLLLLLLLFFFFFFFFFFFQQQQQQQQQTTTTNNGNNNNNNNDDDTTEDDDKKKDKKKKKKKKKKKKKXUUUUUUUUUUCCCEEEFFFFZZZZFFFFFFUFFFFXSIICXIYYYYYYYYY\n" +
            "JJKKKKKKKKKKKKKKVVVKLLLLLLLLGFFFFFFFFFFFQQQQQQQQTTTTNNGGGGNNNNDQQEEEEEEKKKKKKKKKKKKKKKKXXUUUUUUUUUUEEEEEEEEZZZZZZFFFFFFFFFFFFNNICCYYYYYYYYYY\n" +
            "JJKKKKKKKKKKKKKVVVVVVLLLLLLLLQFFFFFFFFFFFFQQQQQQTTTTGGGGGNNNNEEEEEEEEEEEKKKKKKKLKKKKJJJXXUUUUUUUUEEEEEEEEEDZZZZZZZFFFFFFFFFFFFNFCCCYYYYYYYYY\n" +
            "JJKKKKKKKKKKKKVVVVVVVVLLFFLLLFFFFFFFFFFFFFQQQQQQTTTTGGGGGNNNNNEEEEEEEEEEKKKKKLKLLTTTTTJJUUUUUUUUUUEEEEEEEEEZZZZZZZFFFFFFFFFFFFFFCCCYYYYYYYYY\n" +
            "JJKKKKKKKKKKKVVVVVVVVVLLFFFLFFFFFFFFFFFCZFQQQQQQTTTGGGGGGGNNNNEEEEEEEEEEEEEEKLLLLTTTTTTJJUUUUUUUUUEEEEEEEEEZZZZZZFFFFFFFFFFFFFCCCCCYYYYYYYYY\n" +
            "JJJJJKKKKKKKKVVVVVVVVVLFFFFFFFFFFFFFFCCCQQQQQQQQTGTTGGGGGGGNNNEEEEEEEEEEEEELLLLDDTTTTTTJJUUUUUUUUUEEEEEEEEEZZZZZZZFFFFFFFFFFFFFCCCCYYYYYYYYY\n" +
            "JJJJJKKKXKKKKKVVVVVVVVFFFFFFFFFFFFFFFCCEOQQQGQQQGGGGGGGGGGGNNNNEEEEEEEEEEDLLLLLDDTTTTTTJJJUUUUUZUUUEEEEEEEEZZZZZZZZQQFFFFFFFFFCCCCCYYYYYYYYY\n" +
            "JDDDKKKXXXXKKVVVVVVVVVFFFFFFFFFFFFFFFFCEEEEGGQQQGGGGGGGGGGGGNNNEEEEEEEEEEDDYLDDDDTTTTTTJJJUUUUZZUUZZEEEEEEEZZZZZZZZZQQQFFFFFFFFCCCCYYYYYYYYY\n" +
            "JTDDIIXXXXXKKKVVVVVVFFFFFFFFFFFFFFFFCCCEEEGGGGQGGGGGGGGGGGGGNNNENEEEEEEEEDDDLDDDDTTTTTTJJJUUUOZZZZZZZEEEDDEZZZZZZZZZQQQFFFFEFFCCCCCYYYYYYYYY\n" +
            "JDDDXXXXXXXXXKKVVVIVFFFFFFFFFFFFFFFFCCCEEEEEGGGGGGGTGGGGGGGGNNNNNNNEEEDDDDDDDDDDDTTTTTTJJJOOOOZZZGZZZZEEZZZZZZZZZZZZNQQFHHHFFGCCCYYYYYXYYYYY\n" +
            "JJDDDXXXXXXXXKXFFFFVFFFFFFFFZZFFFFFBBBCEEEEGGGTGTGTTGGGGGGGGNNNNNNNDDDDDDDDDDDDDDTTTTTTJJJOOOOGGZGZZZZZZZZZZZZZZZZZQNQQFHHHGGGGGGTXYXXXYXYYY\n" +
            "JDDDDXXXXXXXXXXFFFFFBBBBBFFFZZOZFZBBBBBBTTTGTTTTTTTTGAAAAAAAAANNNNNNDDDDDDDDDDDOOTTTTTTTTTTTOOOGGGGGZGGZZZZZZMZZZZQQNQQFHGGGGGGGGTXYXXXXXXYB\n" +
            "JDDDDXXXXXXXXFFFFFFFBBBBBFFZZZZZFZZBBBBTTTTTTTTTTTTTTAAAAAAAAANNNNFFVDDDDDDDDDDDOTTTTTTTTTTTOOGGGGGGGGGZZGZBZZBZZNNNNQQFGGGGGGGGGXXXXXXXXXXB\n" +
            "JDDDYYXUXXXXXFFFFFFFBBBBBFZZZZZZZZZZBBBBTTTTTTTTTTTAAAAAAAAAAANNFFFFVVDDDDDDDDDDOLTTTTTTTTTTOOGGGGGGGGGGGGBBBBBBBNNNNQQQQCCGGGGGSSSXXXXXXXXB\n" +
            "JNJDYYUUUXXXXFXXXFFFBBBBBFZZZZZZZZZZZBBBBTTTTTTTTTCAAAAAAAAAAANFFFFFFFHDDNDDDDDDOLTTTTTTTTTTOOOGGGGGGGGGGGGBBBBBBBBNNNQCCCCGGGGGGSXXXXXXXXXX\n" +
            "JJJUUUUUUXXXXXXXXXFFBBBBBFZZZZZZZZZZZBZZBTTTTTTTTTAAAAAAAAAAAAFFFFFFFFHDDNNNDDDDDLTTTTTTTTTTOOGGGGGGGGGGGBBBBBBBBBNNNNNNCCCCGLGGSSXXXXXXWXXX\n" +
            "JJJXUJJUUXXXXXXXXDFFBBBBBFOZZZZZZZZZZZZZBBWWWTTTGGGGGGGGAANFFFFFFFFFFFHDFNNNDDDDDDTTTTTTTTTTTOGGGGGGGGGGGBBWBBBBBNNNNNNCCCCCGLLGGXXXXXXXXXXX\n" +
            "JJJUUUUUUUXXXXCXXFFFBBBBBFZZZZZZZZZZZZZZBBWWWWTTGGGGGGGGAAFFFFFFFFFFFFFFFNNNNNNPDOTTTTTTTTTTTOZGGGGGGGGWWWWWBWWWNNNNNNNNCCCCGLLGHHHXHHHXHHHX\n" +
            "GJUUUUUUUUXXXXCXXFGGBBBBBFZZZZZZZZZZZZZZZBBWWWTAGGGGGGGGAAFFFFFFFFFFFFFFFNNNNPPPDOTTTTTTTTTTTZZGGGGGGGWWWWWWWWWNNNNNNNNNNNCCGHHHHHHXHHHHHHHX\n" +
            "UUUUUUUUUUXXXXCVVFCGBBBBBJJZZZZZZZZZZZZZZBBWWWWAGGGGGGGGNNFFFFFFFFFFFFFFSNNNNNNDKOTTTTTTTTTTTZZZZGGGGGGWWWWWWWWWWNNNNNNNCCCGGHHHHHHHHHHHHHHH\n" +
            "UUUUUUUUUUUXCCCCCRCCCCCJJJJJZZZZZZZZZZBBBBBWWWWAGGGGGGGGNNNNFEFFFFFFFFFFFNNNNNNDDDDTTTTTTTTTTZZZZZGGGGGWWWWWWWWNNNNNNNNNNCCCGGGHHGGGHHHHHHHH\n" +
            "UUUUUUUUUUUUUCCCCCCCCCCCCJJZZZZZZZZZZBBBBBWWWWWAGGGGGGGGNNNNEELFFFFFFFFNNNNNNNNDDDDTTTTTTTTTTTTZGGGGGGGWWWWWWWWNNNNNNNNNCCCCGGGGGGGHHHHHHHHH\n" +
            "CUUUUUUUUUUUUUCCCCCCCCCCCCOZZZZZZZAZBBBBBBBWWWWAGGGGGGGGNNNEEELFFFFFFFFFNNNNNNNDDDDDDDDTTTTTTTTZZGGGGGWWWWWWWWWNNNNNNNNNNCCCGGGGGGGHHHHHHHHH\n" +
            "UUUUUUUUUUUUUBBCCCCCCCCCCCOZZZZZZAAABBBBBBIIWWIAGGGGGGGGNNNNEELFEAFFFFFFNNNNNNNNNDDDDDDTTTTTTTTZZGGGGWWWWWWWWWWNNNNNNNCCCCCCGGGGGGHHHQHHHHHH\n" +
            "MMUUBBUUUUBUBBBCCCCCCCCCCCOZZZZZZZAAAMBBBGGGGGGGGGGGGGGGKKEEEEEEEEEFFFNNNNNNNPNNNDDDDDDTTTTTTTTZGGGGGGWWWWWWWWWWNENNNGCCCCCCGGGGGGGHQQQHHHHH\n" +
            "MMUUUBBBBUBUBBBCCCCCCCCCCCOOOOOZOOOAAMMBBGGGGGGGGGGGGGIKKKKEEEEEEEEFFFFNNNNNNNNDDDDDDDDDKKZTTTTZZGGGGGGYWWWWWWWWEEGGMGCCCCCGGGGGGGGHHHQQHHHH\n" +
            "MMUUUBBBBBBBBBBCCCCCCCCCCOOOOOOOOOOOOMMMBGGGGGGGGGGGGGIIKKKKEEEEEEEEFFFNNNNNNNNDDDDDDDDDKKZTTTTZZZGXGYYYYWWWWWWWWWGOGGCCCCGGGGGGGHHHHQQQHHHH\n" +
            "MMUBSBBBBBBBBBBBBCCCCCCCOOOOOOOOOOOOMMMMMGGGGGGGGGGIIIIKKKKKEEEEVEEEFFFFNNNNNNNNNDDDDDDDKZZTTTTZZAYYYYYYYWWWWWWWWWGGGGCACCGGGGGGGHHHHQQQHQQQ\n" +
            "MBBBBBBBBBBBBBBBBBCCCCOOOOOOOOOOOOOOMMMMMGGGGGGGGGGIIIIKKKKKKKEEVVEEFFVVNNNNNNNDDDDDDDDVKZZTTTTTTTTOJYYYYYWWWWWWWGGGGGCAAAHPCGGDGHHHQQQQHQQQ\n" +
            "MMMBBBBBBBBBBBBBBBJJOOOOOOOOOOOOOOOOMMMMMGGGGGGGGGGIIIIKKKKKKKKKKVVVVVVVNNNNNNNNNDDDVVVVKKKTTTTTTTTJJYYYYYYYYWWWZGGGGGGAAAPPPIIGGHHHHUQQQQQQ\n" +
            "MMBBQQBBBBBBBBBBBJJJJOOOOOOOHHHVVOKOMMMMMIIIIIIIIIIIIIIKKKKKKKKKKKVVVVVVNNNNNNNNNDDVVVVVKTTTTTTTTTTJJYYYJYYYYYYGGGGGGAAAAAPPPIIPPAAHHUUUCQQQ\n" +
            "MQQQQQBBBBBBBBJJBJJJJJJOOOOHHHHHVVKKMMPMKKKAIIIIIIIIKKKKKKKKKKKKVVVVVVVVVNNNNCNNDVVVVVVVVTTTTTTTTTTJJJJJJYYYYYGGGGGGGGGAAAPPPPPPPAAHHUUUCCCQ\n" +
            "MQQQBBBBBBBBBJJJJJJJJJJJJOHHHHHHHVKKMKKKKAZAIIAAIIIIKKFKKKKKKKXXXVKVVVVVDDNNNCCCVVVVVVVVVTTTTTTTTTTJJJJJJYYYYYGGGGGGGPPPPPPPPPQPPACCCCCCCCCQ\n" +
            "MQQQBQBBBBBBBJJJJJJJJJJJOOHHHHHHHHKKKKKKKAAAAAAAIAIIFKFFKKKKXXXXXKKKVVDDDDNNDVVVVVVVVVVVVTTTTTTTJJJJJJJJJJYYYYGGGGGGGGGPPPPPPPPPPAACCCCCCCCC\n" +
            "QQQQQQQBBBBBBJJJJJJJJJJJJOHHHHHHHHHKKKKKKAAAAAAAAAAAFFFFKKKKXXXXXKKKVVDDDDDDDDVVVVVVVVVVVTTTTTTTJJJJJJJJJYYYYYGGGGGGGGGGPPPPPPPPPPAACCCCCCCY\n" +
            "QQQQQQQQJBBBBBJJJJJJJJJJOOOHHHHHKHKKKKKKKAAAAAAAAAAAFFFFXXXXXXXXXKKKVVDDDDDDVDVVVVVVVVVVVTTTTTTTJJJJJJJJJJJYYYGGGGGGGGGGGPPPPPPPPPPCCCCCCCYY\n" +
            "QQQQQQQBBBBBBJJJJJJJJJJJOOOFFFFKKHKKKKKAAAAAAAAAAAAAFFFFXXXXXXXXKKKVVVDDDDDDVVVVVVVVVVVVJTTTTTTTYYJJJJJJJJYYYYYGGGGGGGGGPPPPPPPPPPCCCCCCCYYY\n" +
            "QQQQQQQQQBBBBBJJJJJJJJJJOOOOOFFKKKKKAAAFAAAAAAAAAAAFFCCCXXXXXXXXKKVVVDDDDDDDVVVVVVVVVVVVJTTTTTTTJYJJJJJJJJJYYYGGGGGGZGGVPPPPPPPPPPCCCCCCCYYY\n" +
            "QQQQKKQQQQBBBJJJJJJJJJJEOOOOFFFAKKKAAAAAAAAAAAIIIIIIFFFCXXXXXXXXXXXXXXXDDDDDVVVVVVVVVVVVYTTTTTTTJYYJJJJJJYYYYYYGGGGGZZUZPPPPPPPPPCCCCCCCCCYY\n" +
            "QQQQQKKKQQBBBJJJJJJJXNNEEOOOOAAAACAAAAAAAAAAAAIIIIIICCCCXXXXXXXXXXXXXXXDDDDDVDVVVVVVVVVVYYYYYYJJJYYYJJJJJYYYYYYYGGZGTZUZBPPPPPPPPVCCCEEEECYY\n" +
            "QQQQLBBKKBBBBBJJJJJJXNNNOOOQQQQAAAAAAAAYAAAAAAIIIIIIPPCCXXXXXXXXXXXXXXXRRDDDDDVDDVVVVVVVYYYYYYYYYYYYYYYYYYYYYYYYYZZZZZZZZPPPPPPPPVCCCEEEEEYY\n" +
            "QQQQBBBBBBBBBBJJJJJJJNNOOQQQQQQAAAAAAAAAAAAAAAIIIIIIPACCXXXXXXXXXXXXXXXRRDDDDDDDDVVVVVVVYYYYYYYYYYYYYYYYYYYYYYYYYYZZZZZZZUPEPEPPPPCCEEEEEYYY\n" +
            "AAAABBBBBBBBBBJJJJJJJJJQQQQQQQAAAAAAAAAAAAAAAAIIIIIIAAFYCCCCCCXXXXCYDDDDDDDDDDDDDDDVVVNNYYYYYYYYYYYYYYYYYYYYYYYYYYZZZZZZZUEEEEEPPEEEEEEEEEYY\n" +
            "AAAAABBBBBBBBBBJJJJJJJQQQKQQQQAAAAAAAAAAAFAAAAIIIIIIFFFCCCCCCCXXXXCYDDDDDDDDDDDDDDNNNNNNNYYYYYYYYYYYYDDDDYDDYYYYZZZZZZZZZZEEEEEEEEEEEEEEEEEY\n" +
            "AAAAAVABBBBBBBBQJJJJJQQQKKKQKAAWAAAAAAAAAAAAAAIIIIIIFNFNNNNNNNCCCCCYYDDDDDDDDDDDDDDNNNNNNYYYYYYYYYYYDDDDDDDYYYYYZZZZZZZZZZZEEEEEEEEEEEEEEEEY\n" +
            "AAAAAAABBBBBBBBQQJJJQQQQQKKKKKAWWAAAAAMMAAAAAAIIIIIIFNFNNNNNNNCYCYYYYDDDDDDDDUDDDDDDDNNNNYYYYYYYYYYYDQDDDDDYYYYZZZZLZZZZZZZEEEEEEEEEEEEEEEEY\n" +
            "AAAAAAAAAAAABBBQQQQQQQQQQQKKKKWWWAAAAAAAAAAAAAIIIIIIFFFNNNNNNNCYCYYYYYDDDDDDDDIIIDDDDNNNYYYYYYGYYYYDDQDXXDDDDYYZLLLLZZZZZZZEEEEEEEEEEEEEEEEY\n" +
            "AAAAAAAAAAAEBBQQQQQQQQQQQQQQKWWWWWWAAAAAAAAAAAAAFFFFNNNNNNNNNNYYYYYYYYYYDDWDDDDIIDDDDDNYYYYTYYYYYYYYQQQXXDDDXYYZLLLLLLZZZZEEEEEEEEEEEEEEEEEY\n" +
            "AAAAAAAAAAEEBBGQGQQQQQQQQCCCKCWCCCWWWWWAAHAAAAAAFFFFNNNNNNNNNNYYYYYYYYYDDWWYDLDDIIIDDDDHHQQQYZYYYYQQQQXXXDDDXLYXLLLLLZZZVZEEEEEEEEMEEEEEMMMM\n" +
            "AAAAAAAAAAEEEGGGGGQGGGQQQCCCCCCCCWWWWWWAAAAAAAAAFFFFNNNNNNNNNNQYQQQYYYYYYYYYGDDDDDDDDDDDHQQQQQQQQYQQQQQXXXDDXXXXLHHHLZVVVZEEEEEEEEMEEEMMMMMM\n" +
            "AAAAAAAAAAEEGGGGPGGGGGCCCCCCCCCCCRRRRWWWWWWFFFAFFFFFNNNNNNNNNNQQQQQYYYYYYYYYGDDDDDDDDDDQQQQQQQQQQQQQXXXXXXXXXHHXHDHHLZZZZZEEEEEEMMMEEMMMMMMM\n" +
            "AAAAAAAAAWGGGGGGGGGGGGGCCCCCCCCCCRRRRWWWWWWWWFAFFFFFNNNNNNNNNNYYQQQQQYYYYYYYGGDDDDDDDRDQQQQQQQQQQQQQXXXXXXXXXHHHHHHHLLLEEEEEEEEMMMMMMMMMMMMM\n" +
            "AAAAAAAUAWWGGGGGGGGGGDCCCCCCCCCCCRRRRRRWWWWWWFFFFFFFNNNNNNNNNNYYQQQQQYJYYYYYYGDDDDDDFFQQQQQQQQQQQQQXXXXXXXXXXHHHHHHHLLLEEEEEEEEMMMMMMMMMMMMM\n" +
            "AAAAAAAAAAAGGGGGGGGGCCCCCCCCCCCXCCRRRRWWWWWWWWWDFFFFNNNNNNNNNNYQQQQQYYJYYYYDDDDDDDFDFFFQQQQQQQQQQQXXXXXXXXHHHHHHHHHHHHHEEEEEWWEMMMMMMMMMMMMM\n" +
            "AAAAAAAAAAGGGGGGGGGGGCCCCCXCCICXXKKRRWWWWWWWWWDDFFKKNNNNNNNNNNQQQQQQYJJYYYYDDDDDDFFFFFFCCCCCCCCQQQXXXXXXXXHRHHHHHHHHHZZNZZEEEWWMMMMMMMMMMMMM\n" +
            "AAAAAAAAAAGGGGGGGGGGCCLCCCCCCCKXKKKWWWWWWWWWWWWDFKKKNNNNNNNNNQQTQRQQQJJYYYYDDDDDDFCCCCCCCCCCCCCQQQQQXXXXXXXXHHHHHHZZZZZZZZZEEWWAMMMMMMMMMMMM\n" +
            "IIIIAAIAAAAIGGGGGGGGGCLCCCCCOCKKKKKKWWWWWWWWWWWDDKKKKKKKKKKKKQQQQRRQTTJJYYYDDDDDFFCCCCCCCCCCCCCQQQXXXXXXXXXXHHHHHHZZZZZZZZZZWWWMMMMMMMMMMMMM\n" +
            "IIIIIIIIAIAIAGGGGGGGGGLNNNCCOOOKKKKKKKKKKWWWWWWWWKKKKKKKKKKKKQQQQQQTTTTJYHYRRRRFFFCCCCCCCCCCCCCQQQQXXXXXXXBBBHHHHZZZZZZZZZZZZWJMMMMMMMMMMMMM\n" +
            "IIIIIIIIIIIIIGGGGGGGGGNNNNCNNONKKKKKKKZKSWWWWWWWWWKKKKKKKKKKKQQQQQQQTTTTTYYRRRRRRFCCCCCCCCCCCCCQQQQXXXXXXXBBHHHZZZZZZZZZZZZZWWWMMMMMMMMMMMMM\n" +
            "IIIIIIIIIIIIIGGGGGGGGGNNNNNNNNNZKKKKKKKSSWWWWWWWWWWKKKKKKKKKQQQQQQQQTTTTTTTUURRRRFCCCCCCCCCCCCCQQQQQXXXXXXXXZHHZZZZZZZZZZZZZZWWWWWMMMMMMMMMS\n" +
            "IIIIIIIIIIIIRAAAAANNGNNNNNNNNNNKKKKKKKSSLWWWWWWWWWWMKKKKKKKKQQQQQQQQQQUUUTUUUURFRFFFCCCCCCCCCCCQQQQQXXXXXXXZZZZZZZZZZZZZZZZZZWWWWWMWWGMMMMMS\n" +
            "IIIIIIIIIIIIAAAAAANNNNNNNNNNNNNKKKKKKKKSLLWWWWWWMWWYKKKKKKKKYQQQQQCQQQUUUTUUUUUFFFFFFFFFFFHHHHHHHHHHXXXXXBXXZZZZZZZZZZZZZZZOZWWWWWWWGGMGMMMG\n" +
            "IIIIIIIIIIIAAAAAAAANNNNNNNNNNNNKKKKKKKLSLLWWCWMMMYYYKKKKKYYYYQQQQQCQQQUUUUUUUUUUFFFFFFFNFHHHHHHHHHHXXXXXXXXXXZZZZZZZZZZZZZZOZZZWWWWWGGGGMGVG\n" +
            "IIIIIIIIIIIAAAAAAANNNNNNNNNNNNNXXKKKLLLLLLLWWMMMYYYYYKYKYYYYYQQQCCCCCQUUUUUUUUUUPFFFFFFFFHHHHHHHHHZZZZAAXXXXXZZZZZZZZZZZZZZZZUUWWWWGGGGGGGGG\n" +
            "IIIIIIIIIIIAAAAAAANNNNNNNNNNNNXXXKKKKLLLLLLMMMMMYYYYYYYYYYYYYQQCCCCCCCUUUUUUUUUUFFFFFFFFFFHHHHHHHZZAAAHAAAXXZZZZZZZZZZZZZZZUUUUUUGGGGGGGGGGG\n" +
            "YIIIIIIIIIIAAAAAAANNNNNNNNNNNNXXXKKKKLLLLLLLMMMMMYYYYYYYYYYYYYYYCCCCCCUUUUUUUUUUFFHFFFFFFHHHHHHHHHZAAAAAAAXXXZZZZZZZZZZZZZZZUUUUUGGGUGGGGGGG\n" +
            "YYIIIIIIIIAAAAAAAANNNNNNNNNNXXXXXXXXXLLLLLLLMMMMMMYYYYYYYYYYYYCCCCCCCCRRUUUUUUUUGFHHHHHHHHHHHHHHHHAAAAAAAAAXXZZZZZZZZZZZZZZZUUUUUUGGGGGGGGGG\n" +
            "YYYIIIIIIIAAAAAAAAANNNNNNNNNNXXXXXXXXLLLLLLLLMMMMMYYYYYYYYYYYYYYCCCCRRRRRUUUCCUUGHHHHHHHHHHHHAHAKKAAAAAAAAAXXZZZZZZZZZZZZZUUUUUUGGGGGGGGGGGG\n" +
            "YYYYINNIIIAAAAAAAAANNNNNNNNXXXCXXXXXXXLLLLLLMMMMMYYYYYYYYYYYYYYRRRRRRRRRRUCUCCCCHHHKHHHHHHHHHAAAAAAAAAAAAAAAXZZZZZZZHHZZZZUUUUUUGGGGGGGGGGGG\n" +
            "YYYYINIIIAAAAAAAAAAAAQNONICCCXCCXXXXXXXXLLLLMMMMMMYYYYYYYYYYYYRRRRRRRRRRRCCCCCCZZHHHHHHTTHHHHHAAAAJAAAAAAAAAAEZZZZZHHHZZZZUUUUUUGGGGGGGGGGGG\n" +
            "YYYYYAAAAAAAAAAAAAAAANNQQQCCCCCCXXXXXXXXLMMLMMMMMMYYYYYYYYYYYYRRRRRRRRRRCCCZZCCZZTTTTTTTTTHHHHAJJJJAAAAAAAAAAAZZZZZZHHZZZZUUUUUUGGGGGGGGGGGG\n" +
            "YYYYYAAAAAAAASSAAAAAAIQQQQCCCCCCXXXXXXXXLMMMMMMMMMMMMMMYZYRRYRRRRRRRRRRRZCCZZZCCZZTTTTTTCTHHHHHHJJJAAAAAAAAOOOZZPPPOHUUCUUUUUUUUUGGGGGGGGGGG\n" +
            "YYYEEEEAAAAASSSAAAAAAQQQQCCCCCCCCCCXXXXXLMMMMMMMMMMMWWMWRRRRYYRRRRRRRRRRZZZZZZZZZBTTTTTPTTHHHHHHHJJJJAAXAAAAAZZZPOOOOOUUUUUUUUGGGGGUGGGGGGGG\n" +
            "YEEEEEEAAAAASSAAAAAAQQQQQCCCCCCCCCCCCXXXLMMMMMMMWWMWWWMWRRRRRRRRRRRGRRRZZZZZZZZZZZTTTTTTTTTTHHHHHJJJJAAAAMMMMMZZZHHOONNUVUUUUUGGUGUUUGGGGGGG\n" +
            "YEEEEEEDAAASSSAAKQQAQQQVQCCCCCCCCCCCXXXKKMMMMMMMWWWWWWWWRRRRRRRRRRRRRRZZZZZZZZZZZZZTTTTTTTTTTJJJJJJJJJAAMMMMMMMZZHHOOONVVVVUUUUUUGUUKGGGGGZG\n" +
            "YEEEEEAAAAAASSKKKQQQQQVVQCCCCCCCCCCCCKXKMMMMMMMMMMWWWWWWRRRRRRRRRRRRRZZZZZZZZZZZZZZTTTTTTTTTTTJJJJJJJJJTMMMMMMMZZHHOVVVVVVVVUUUKUUUUKKGGGGGG\n" +
            "EEEELEEEGAASSSSCKKVQQVVVHCCCCCCCCCCCKKKKKKKMMMMMWWWWWWWPWRRRRRRRRRRRIMMZZZZZZZZZZTTTTTTTTTTTTTJJJJJJJJTTTMMMMMMZJJHHHHHVVVVVVKUKKKUUKKKKKGUU\n" +
            "NEEEEEEEEARWSSSSTKVVVVVVHCCCCCCCCCCKKKKKKKKKMMMMWWWWWWWWWRRRRRRRRIIRIMMZZZZZZZZZZTTTTTTTTTTTTJJJJJJJJJTTTTMTTTTTJJJHHHHVVVVVKKKKKKKKKKKKKKKU\n" +
            "EEEEEEEERRRWWSSSSSSVVVVVHCCCCCCCCCCKKKKKKKKKKMMMMWWBWWWWWRRRRRRRRBBBBBBBBBBZZZZZZTTTTTTTTTTTTJJJJJJJJJTTTTTTTTTTTHHHHHHVVVVVKKKKKKKKKKKKKKKK\n" +
            "HEEEEEEERWWWWHHSSSSSVVVVVVCCCOCCCCKKKKGKKKKKKMMMMMWBWWWWWRRRRRRRRBBBBBBBBBBZZZZLZTTTTTTTTTTJJJJJJJJJTTTTTTTTTTTTTTHHHHVVVVVVKKPKKKKKKKKKKIII\n" +
            "EEEEEEEEERWWWHHSWSSSSVVVVVCCCCCKKKKKKKKKKKKKMMMBBBBBBWWWBRRRRRRRRBBBBBBBBBBZYZZTTTTTTTTTTTTTCJCJJZZJTTTTTTTTTTTTTTTHHVVVVVVKKKKKKKKKKKKKKIII\n" +
            "EEEEEEEEEEEWWWWWWVVVVVVVVVVVCCCKKKKKKKKKKKKQBBBBBBBBBBBVBRRRRRRRIBBBBBBBBBBZZZXTTTTTTTTTTCTCCCCJCZZNTTTTTTTTTTTTTTTHHVVVVVVKKKKKKKKKKYKKIIII\n" +
            "EEEEEEEEEEEWWWWWWVVVVVVVVVVVVCKKKKKKKKKKKKIQBQBBBBBBBBBBBBBRRRRRBBBBBBBBBBBZXXXGKTTTTTTTTCCCCCCCCCNNTNTTTTTTTTTCVVVVVVVVVVVKKKKKKKKKKYYYYIII\n" +
            "EEEEEBBEEWWWWWWWWVVVVVVVVVVVVVVKKKKKKKKKKIIQQQQBBBBBBBBBBBBRUUUUUBBBBBBBBBBIXXXGGTTMTTTTTCCCFFFFFFFNNNTTTTTTTTTVVVVVVVVVVVVVVKKKKKKKKKKYYYII\n" +
            "EEEEEBBBEWWWWWWWWVVVVVVVVVVVVVVVKKKKKKKKKIIIQQBBBBBBBBBBBBRRUUUUUBBBBBBBBBBIXXXGCTTMMTTTTCCCFFFFFFFNNNNNTTTTDTNVVVVVVVVVVVVVVKKVKKKKYKHYYYII\n" +
            "LBEBBBBBJWWWWWWWVVVVVVVVVVVVVVKKKKKKKKKKIIIIIINTBBBBBBBBBBRRUUUUUBBBBIIIIIIIIGGGGGMMMCTCCCCCFFFFFFFNNNNNDDTDDDDVVVFVTTTVTVVVVKVVVYYYYYYYYYYY\n" +
            "BBBBBBBBJJJWWWWWWWVVVVMVVVVVVVKKKKKKKKKKKKIIIINTBBBBBBBBBRRRUUUUUBBBBIIIIIIIIIGGGGGMMCCCCCCCFFFFFFFNNDDDDDDDDDDDDTTTTTTTTVTTVVVVVVVYYYYYYYYY\n" +
            "BBBBBBBBJJJJJWWWWWWGGGVVVVVVVKKKOKKKKKKKKKIIINNNBBBBBBBBBRRRUUUUUBBBBIIIIIIIIIGGHMMMCCCCCCCCFFFFFFFNNDDDDDDDDDDDDCTTTTTTTTTTVVVVVVVYYYYYYYYY\n" +
            "BBBBBBBJJJJJWWWWWWWWGGGGVVVVVKKOOOKKKKKKKKKIKKNUUUUBBBBBBRRRUUUUUBBBBIIIIIGGGGGHHHCCCCCCCCCCCCCCOOODDDDDDDDDDDDTTTTTTTTTTTTTVVVVVYYYYYYYYYYL\n" +
            "BBBBBBJJJJJJJWWWWQQQGGGGVVVVKKKOOOOKKKKKKKKKKKUUUUUBBHBBBBRRJJJJBBBBBIIIIIGGGGHHHHHCCCCCCCCCCCCCOOOODDDDDDDDDDDTTTTTTTTTTTTTTVVVVVYYYYYYYYYY\n" +
            "BBJJJJJJJJJJJWWQQQQQQGGGGVGGGKOOOKKKKKKKKKKKKKUSSUUUJUBBBURRYYYJJJIIIIIIIIGGGGHHHHHHHHCCCCCCCCCOOOOOODDDDDDDDDTTTTTTTTTTTTTTTVVAAVYYYYYYYYYY\n" +
            "BBJJJJJJJJJJWWQQQQQQGGGGGGGKKKKKOKKKKKKKKKKOKKUUUUUUUUBBUUUQQYYJJJIIIIISIIIGGGGHHHHHHHHCHCCCCCCCOOOODDDDDDDDDDTTTTTTTTTTTTTTAVAAAYYYYYYYYYYY\n" +
            "JJJJJJJJJJJJJWWQQQQQGGGGGGGGKKKKKKKKKKKKKKKOOKUUUUUUUUUUUUUQQQJJJJIIIIIGGIGGGGGHHHHHHHHHHCCHCCCCCCCDDDDDDDDDDDDTTTTTTTTTTTAAAAAAAAYYYYYYYYYY\n" +
            "JJJJJJJJJJJJWWWQGQGQGGGGGGGGGKKCKKKKKKKKKOOOOJUUUUUUUUUUUUQQQVQJJIIIIIZZGGGGGGGHHHHHHHHHHHHHCGCCCBKBPDDDDSDDDDDTTTTTTTTTTTTTAAAAAAYYYYYYYYYU\n" +
            "JJJJJJJJJJJJJJBGGGGGGGGGGGGGGKCCKKKKKKKKKOOOOOUUUUUUUUUUUUQQQQQJJJIZZZZZGGGGGGGHHHHHHHHHHHHCCGCBBBBBBSDGDDDDDDTTTTTTTTTTTTTTAMAAAAYYYYYYYYYU\n" +
            "JJJJJJJJJJJBJJBGGGGGGGGGGCCGCCCCCKKKKKKKAOOOOOOUUUUUUUUUUUQQQQQQZZIZZZTZGGGGGGGHHHHHHHBHHHHBBBBBBBBBDDDDDEEDDDEQQLTTTTTTTTTCMMAYYYYYYYYYYYYU\n" +
            "JBJJJJJJJJJBBBBBGGGGGGGGGCCCCCCCCCCCKKKAAOOOOOOOOUUUUUUUUUQQQQQQQZZZZZXXXGGGGGGHHHHHHHBBBBBBBBBBBBBBBDDDDEEEDEEQQQIIITTTTTTTTMMMYCYYYYYYUUUU\n" +
            "BBBBJLLLQJBBBBBBBGGGGGGGGGCHHCCCCCCCWKKKAAOOOOOOOOOOUUUUUUQQQQQQQZZZZXXXZZZGGHHHHHHMBBBBBBBBBBBBBBBBDDDDDEEEEEQQQQIQITTTKTTTMMMMMCYYYYYUUUUU\n" +
            "BBBBJLLLLLLBBBBBBGGGGGGGGGGHHCCCCCCCCKAAAOOOOOOOOOOOUUUUUUQQQQQZZZZZZXXXZZZZGGHMMHHMBBBBBBBBBBBBBBBQDDDDDEEEEEEQQQQQITTTKKKTMMMMMCYYYYYUUCUC\n" +
            "BBBBBBLLLBBBBBBBBGGGGGGGGGCCCCCCCCCCCAAAAOOOOOOOOOOOOOOUUUTQQQQZZZZZZZZZZZZZGGGGMMMMBBBBBBBBBBBBBBBQDDDDEEEEEEQQQQQQQKKKKKKMMMMMCCCCCCCCCCCC\n" +
            "BBBBBLLLLLBBBBBBBBBBGGGGGGCCCCCCCCCAAAAAOOOOOOOOOOOOOOOOCCOQQZQZZZZZZZZZZZZZGGGGMMMMBBBBBBBBBBBBBBBDDDDDDEEEEEEQQQQKQKKKKKKMMMMMCCCCCCCCCCCC\n" +
            "BBBBBBBBBBBBBBBBBBBGGGGNGJJJCCCCCCAAAAAAOOOOOOOOOOOOOOOOOOOZZZZZZZZZZZZZZZZZZZZZMMMMMBBBBBBBBBBBBBBTTTTDEEEEEEEEEQKKKKKKKKKMMMMMMMMCCCCCCCCC\n";   
}

function getTestData() {
    return  "AAAA\n" +
            "BBCD\n" +
            "BBCC\n" +
            "EEEC\n";
}

